modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/Bawnorton/Dynamic-Trim/issues"
license = "MIT"

[[mods]]
modId = "dynamictrim"
version = "${version}"
displayName = "Dynamic-Trim"
authors = "Bawnorton"
description = '''
${description}
'''
logoFile = "assets/dynamictrim/icon.png"

[[mixins]]
config = "dynamictrim.mixins.json"

[[mixins]]
config = "dynamictrim-client.mixins.json"

[[dependencies.dynamictrim]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"